=== Quipyowert2/bear/bear-factory/schema/0.5/item-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.gamned.org/bear/schema/0.5"
           xmlns="http://www.gamned.org/bear/schema/0.5"
           elementFormDefault="qualified">
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="inherit"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="fields"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="new_default_value"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="remove_field"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="category" type="xs:string" use="required"/>
      <xs:attribute name="box_color" type="xs:string"/>
      <xs:attribute name="fixable" type="xs:boolean" default="true"/>
      <xs:attribute name="url" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="description" type="xs:string"/>
  
  <xs:element name="inherit">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="class"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="set" />
        <xs:element minOccurs="0" maxOccurs="1" ref="interval" />
        <xs:element name="default_value" minOccurs="0" maxOccurs="1" type="xs:string" />
	<xs:element minOccurs="0" maxOccurs="unbounded" ref="after" />
      </xs:sequence>

      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="animation"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="font"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="item_reference"/>
            <xs:enumeration value="real"/>
            <xs:enumeration value="sample"/>
            <xs:enumeration value="sprite"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="u_integer"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" type="xs:ID" use="required"/>
      <xs:attribute name="required" type="xs:boolean" default="false"/>
      <xs:attribute name="list" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="after">
    <xs:complexType>
      <xs:attribute name="field" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="set">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="element">
          <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interval">
    <xs:complexType>
      <xs:attribute name="from" type="xs:decimal" use="required"/>
      <xs:attribute name="to" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="new_default_value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="remove_field" type="xs:string"/>

</xs:schema>

=== Quipyowert2/bear/bear-factory/item-description/generic/camera.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::camera" category="control/camera" fixable="false" box_color="#343C66" url="http://www.gamned.org/wiki/index.php/camera">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::item_with_text_interface</class>
  </inherit>
  <description>A simple camera.</description>
  <fields>
    <field type="real" name="camera.valid_min.x">
      <description>The minimum valid X-position of the camera.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="camera.valid_max.x">
      <description>The maximum valid X-position of the camera.</description>
      <default_value>The width of the level</default_value>
    </field>
    <field type="real" name="camera.valid_min.y">
      <description>The minimum valid Y-position of the camera.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="camera.valid_max.y">
      <description>The maximum valid Y-position of the camera.</description>
      <default_value>The height of the level</default_value>
    </field>
    <field type="real" name="camera.max_move_length">
      <description>The maximum movement of the camera.</description>
      <default_value>infinity</default_value>
    </field>
    <field type="real" name="camera.max_zoom_length">
      <description>The maximum change of the size.</description>
      <default_value>infinity</default_value>
    </field>
    <field type="boolean" name="camera.active">
      <description>Indicates if the camera start in active mode.</description>
      <default_value>false</default_value>
    </field>

    <field type="real" name="camera.size.min_width">
      <description>The minimum width of the camera.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="camera.size.max_width">
      <description>The maximum width of the camera.</description>
      <default_value>The width of the level.</default_value>
    </field>
    <field type="real" name="camera.size.min_height">
      <description>The minimum height of the camera.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="camera.size.max_height">
      <description>The maximum height of the camera.</description>
      <default_value>The height of the level.</default_value>
    </field>
  </fields>
  <new_default_value name="base_item.artificial">true</new_default_value>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/decorative_flow.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::decorative_flow" category="decoration" box_color="#387F8A" url="http://www.gamned.org/wiki/index.php/decorative_flow">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::basic_renderable_item</class>
    <class>bear::item_with_decoration</class>
    <class>bear::item_with_activable_sides</class>
  </inherit>
  <description>A rectangle in which some decorative sprites move linearly to
  simulate a flow.</description>
  <fields>
    <field type="real" name="decorative_flow.max_speed.x">
      <description>The maximum speed of flow on x axis.</description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="decorative_flow.max_speed.y">
      <description>The maximum speed of flow on y axis.</description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="decorative_flow.min_speed.x">
      <description>The minimum speed of flow on x axis.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="decorative_flow.min_speed.y">
      <description>The minimum speed of flow on y axis.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="decorative_flow.items_per_second">
      <description>The number of items per second in average.</description>
      <default_value>1</default_value>
    </field>
  </fields>
  <new_default_value name="base_item.artificial">true</new_default_value>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/forced_movement/forced_tracking_creator.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::forced_tracking_creator" category="control/movement" box_color="#CAFF00" fixable="false" url="http://www.gamned.org/wiki/index.php/forced_tracking_creator">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::forced_movement_tag</class>
    <class>bear::forced_movement_creator_with_reference</class>
  </inherit>
  <description>This class creates a forced movement of type "forced_tracking", applies it to itself then die.</description>
  <fields>
    <field type="real" name="forced_tracking_creator.distance.x">
      <description>The distance to keep on the X axis.</description>
      <default_value>auto</default_value>
    </field>
    <field type="real" name="forced_tracking_creator.distance.y">
      <description>The distance to keep on the Y axis.</description>
      <default_value>auto</default_value>
    </field>
    <field type="real" name="forced_tracking_creator.duration">
      <description>The total time of the movement.</description>
      <default_value>infinity</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/star.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::star" category="decoration" box_color="#BE41D1" url="http://www.gamned.org/wiki/index.php/star">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::basic_renderable_item</class>
  </inherit>
  <description>This item displays a star.</description>
  <fields>
    <field type="u_integer" name="star.branches">
      <description>The number of branches in the star.</description>
      <interval from="3"/>
      <default_value>5</default_value>
    </field>

    <field type="real" name="star.ratio">
      <description>The ratio of the inner vertices relatively to the outer
        ones.</description>
      <interval from="0" to="1"/>
      <default_value>0.5</default_value>
    </field>
    
    <field type="real" name="star.border_width">
      <description>The width of the border of the star.</description>
      <interval from="0"/>
      <default_value>1</default_value>
    </field>

    <field type="real" name="star.border_color.red">
      <description>The red component of the color of the border.</description>
      <interval from="0" to="1"/>
      <default_value>0</default_value>
    </field>

    <field type="real" name="star.border_color.green">
      <description>The green component of the color of the border.</description>
      <interval from="0" to="1"/>
      <default_value>0</default_value>
    </field>

    <field type="real" name="star.border_color.blue">
      <description>The blue component of the color of the border.</description>
      <interval from="0" to="1"/>
      <default_value>0</default_value>
    </field>

    <field type="real" name="star.border_color.opacity">
      <description>The opacity of the border.</description>
      <interval from="0" to="1"/>
      <default_value>1</default_value>
    </field>

    <field type="real" name="star.fill_color.red">
      <description>The red component of the color of the inside.</description>
      <interval from="0" to="1"/>
      <default_value>0</default_value>
    </field>

    <field type="real" name="star.fill_color.green">
      <description>The green component of the color of the inside.</description>
      <interval from="0" to="1"/>
      <default_value>0</default_value>
    </field>

    <field type="real" name="star.fill_color.blue">
      <description>The blue component of the color of the inside.</description>
      <interval from="0" to="1"/>
      <default_value>0</default_value>
    </field>

    <field type="real" name="star.fill_color.opacity">
      <description>The opacity of the inside.</description>
      <interval from="0" to="1"/>
      <default_value>1</default_value>
    </field>

  </fields>

  <new_default_value name="base_item.artificial">true</new_default_value>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/forced_movement/forced_path_creator.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::forced_path_creator" category="control/movement" box_color="#CAFF00" fixable="false" url="http://www.gamned.org/wiki/index.php/forced_path_creator">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::forced_movement_tag</class>
  </inherit>

  <description>
    This class creates a forced movement that joins several items in a sequence,
    applies it to itself then die.
  </description>

  <fields>

    <field type="u_integer" name="forced_path_creator.loops">
      <description>How many times the path will be done.</description>
      <default_value>infinity</default_value>
    </field>

    <field type="real" name="forced_path_creator.speed">
      <description>The speed of the moving item</description>
      <default_value>1</default_value>
    </field>

    <field type="item_reference" name="forced_path_creator.path" list="true"
           required="true">
      <description>
        The items to reach in the path, must be non empty.
      </description>
      <after field="forced_path_creator.speed"/>
    </field>

  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/level_loader_toggle.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::level_loader_toggle" category="level loading" box_color="#9B975F" url="http://www.gamned.org/wiki/index.php/level_loader_toggle">
  <inherit>
    <class>bear::item_with_toggle</class>
    <class>bear::base_item</class>
  </inherit>
  <description>This item starts a level when activated.</description>
  <fields>
    <field type="real" name="level_loader_toggle.fade_duration">
      <description>
	The duration of the fading effect before starting the level.
      </description>
      <default_value>1</default_value>
    </field>
    <field type="string" name="level_loader_toggle.level" required="true">
      <description>The path of the level to start, or the name of a game
        variable containing this path.
      </description>
    </field>
    <field type="string" name="level_loader_toggle.transition_layer_name">
      <description>
	The name of the transition layer receiving the fade effect.
      </description>
      <default_value>none</default_value>
    </field>
    <field type="boolean" name="level_loader_toggle.push_mode">
      <description>Indicates if the level must be pushed.</description>
      <default_value>false</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/timer.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::timer" category="time" box_color="#1FBF73" url="http://www.gamned.org/wiki/index.php/timer">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::item_with_toggle</class>
  </inherit>
  <description>A simple timer.</description>
  <fields>
    <field type="boolean" name="timer.countdown">
      <description>Tell if the timer is a countdown.</description>
      <default_value>false</default_value>
    </field>
    <field type="boolean" name="timer.loop">
      <description>Tell if the timer loops when the countdown is
        over.</description>
      <default_value>false</default_value>
    </field>
    <field type="boolean" name="timer.reset_when_reactivated">
      <description>Indicate if the values of the timer are initialized each
	time it is activated.</description>
      <default_value>true</default_value>
    </field>
    <field type="real" name="timer.time">
      <description>The initial time, in seconds.</description>
      <default_value>0</default_value>
    </field>
    <field type="item_reference" name="timer.toggle">
      <description>A toggle toggled when the countdown is over.</description>
      <default_value>none</default_value>
    </field>
  </fields>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
  <new_default_value name="base_item.global">true</new_default_value>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/script/add_script_actor.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::add_script_actor" category="script" box_color="#BA7EFF" url="http://www.gamned.org/wiki/index.php/add_script_actor">
  <inherit>
    <class>bear::base_item</class>
  </inherit>
  <description>An item that adds an actor in a script_director.</description>
  <fields>
    <field type="item_reference" name="add_script_actor.actor" required="true">
      <description>The new actor.</description>
    </field>
    <field type="string" name="add_script_actor.actor_name" required="true">
      <description>The name of the actor.</description>
    </field>
  </fields>
  <new_default_value name="base_item.artificial">true</new_default_value>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
</item>
