=== Quipyowert2/bear/bear-factory/schema/0.5/item-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.gamned.org/bear/schema/0.5"
           xmlns="http://www.gamned.org/bear/schema/0.5"
           elementFormDefault="qualified">
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="inherit"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="fields"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="new_default_value"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="remove_field"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="category" type="xs:string" use="required"/>
      <xs:attribute name="box_color" type="xs:string"/>
      <xs:attribute name="fixable" type="xs:boolean" default="true"/>
      <xs:attribute name="url" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="description" type="xs:string"/>
  
  <xs:element name="inherit">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="class"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="set" />
        <xs:element minOccurs="0" maxOccurs="1" ref="interval" />
        <xs:element name="default_value" minOccurs="0" maxOccurs="1" type="xs:string" />
	<xs:element minOccurs="0" maxOccurs="unbounded" ref="after" />
      </xs:sequence>

      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="animation"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="font"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="item_reference"/>
            <xs:enumeration value="real"/>
            <xs:enumeration value="sample"/>
            <xs:enumeration value="sprite"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="u_integer"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" type="xs:ID" use="required"/>
      <xs:attribute name="required" type="xs:boolean" default="false"/>
      <xs:attribute name="list" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="after">
    <xs:complexType>
      <xs:attribute name="field" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="set">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="element">
          <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interval">
    <xs:complexType>
      <xs:attribute name="from" type="xs:decimal" use="required"/>
      <xs:attribute name="to" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="new_default_value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="remove_field" type="xs:string"/>

</xs:schema>

=== Quipyowert2/bear/bear-factory/item-description/generic/level_loader_progression_item.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::level_loader_progression_item" category="level loading" box_color="#FE2B7A" url="http://www.gamned.org/wiki/index.php/level_loader_progression_item">
  <inherit>
    <class>bear::level_loader_item</class>
    <class>bear::basic_renderable_item</class>
  </inherit>
  <description>An item that fills a bar while loading a level.</description>
  <fields>
    <field type="sprite" name="level_loader_progression_item.sprite" required="true">
      <description>The sprite that grows while the level is loaded.</description>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/item_brick/item_with_decoration.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::item_with_decoration" category="-abstract-" url="http://www.gamned.org/wiki/index.php/item_with_decoration">
  <fields>
    <field type="sprite" name="item_with_decoration.sprite">
      <description>The sprite of the item.</description>
      <default_value>none</default_value>
    </field>
    <field type="animation" name="item_with_decoration.animation">
      <description>The animation of the item.</description>
      <default_value>none</default_value>
    </field>
    <field type="item_reference" name="item_with_decoration.item_to_mimic">
      <description>Display the same sprite than the given item.</description>
      <default_value>none</default_value>
    </field>
    <field type="boolean" name="item_with_decoration.extend_on_bounding_box">
      <description>Indicates if the decoration must be extended on the bounding box. No effect with item_to_mimic option.</description>
      <default_value>false</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/rolling_credits.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::rolling_credits" category="credits" box_color="#59D48F" url="http://www.gamned.org/wiki/index.php/rolling_credits">
  <inherit>
    <class>bear::base_item</class>
  </inherit>
  <description>This items displays rolling credits, ie. a list of
  members of the software team. This list is taken from a custom
  file.</description>
  <fields>
    <field type="string" name="rolling_credits.credits" required="true">
      <description>The path to the credits file.</description>
    </field>
    <field type="real" name="rolling_credits.movement_duration">
      <description>The duration in seconds of the movement of the
      lines.</description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="rolling_credits.fading_duration">
      <description>The duration in seconds of the fading effect when a
      line appears or disappears.</description>
      <default_value>movement_duration/4</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/forced_movement/forced_aiming_creator.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::forced_aiming_creator" category="control/movement" box_color="#CAFF00" fixable="false" url="http://www.gamned.org/wiki/index.php/forced_aiming_creator">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::forced_movement_tag</class>
    <class>bear::forced_movement_creator_with_reference</class>
  </inherit>
  <description>This class creates a forced movement of type "forced_aiming", applies it to itself then die.</description>
  <fields>
    <field type="real" name="forced_aiming_creator.duration">
      <description>The total time of the movement.</description>
      <default_value>infinity</default_value>
    </field>
    <field type="real" name="forced_aiming_creator.max_angle">
      <description>The maximum angle of the direction.</description>
      <default_value>infinity</default_value>
    </field>
    <field type="boolean" name="forced_aiming_creator.apply_angle">
      <description>Tell (true) if we apply the angle of the movement to the
        item.</description>
      <default_value>false</default_value>
    </field>
    <field type="real" name="forced_aiming_creator.max_speed">
      <description>The maximum speed of the movement.</description>
      <default_value>infinity</default_value>
    </field>
    <field type="real" name="forced_aiming_creator.acceleration">
      <description>The acceleration of the item.</description>
      <default_value>infinity</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/hidden_block.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::hidden_block" category="block" box_color="#302CE0" url="http://www.gamned.org/wiki/index.php/hidden_block">
  <inherit>
    <class>bear::block</class>
  </inherit>
  <description>A block that changes its opacity when an oject collides.</description>
  <fields>
    <field type="real" name="hidden_block.opacity.passive">
      <description>The opacity when no item collides.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="hidden_block.opacity.active">
      <description>The opacity when an item collides.</description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="hidden_block.transition_duration">
      <description>The duration of opacity changing.</description>
      <default_value>0.25</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/line.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::line" category="decoration" box_color="#BE41D1" url="http://www.gamned.org/wiki/index.php/line">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::basic_renderable_item</class>
  </inherit>
  <description>This item displays a line between several items.</description>
  <fields>
    <field type="item_reference" name="line.ends" list="true">
      <description>The ends of the segments of the line.</description>
      <default_value>none</default_value>
    </field>
    <field type="real" name="line.width">
      <description>The width of the line.</description>
      <default_value>1</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/game_variable/bool_game_variable_getter_creator.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::bool_game_variable_getter_creator" category="game_variable/expression" box_color="#69DAFF" fixable="false">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::with_boolean_expression_creation</class>
  </inherit>
  <fields>
    <field type="string" name="bool_game_variable_getter_creator.name" required="true">
      <description>The name of the variable to get.</description>
    </field>
    <field type="boolean" name="bool_game_variable_getter_creator.default_value">
      <description>The default value of the variable.</description>
      <default_value>false</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/camera_shaker.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::camera_shaker" category="control/camera" box_color="#D72F93" url="http://www.gamned.org/wiki/index.php/camera_shaker">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::item_with_toggle</class>
  </inherit>
  <description>An item that shakes the camera.</description>
  <fields>
    <field type="real" name="camera_shaker.shaker_force">
      <description>The force to give to shake the camera.</description>
      <default_value>10</default_value>
    </field>
    <field type="boolean" name="camera_shaker.check_camera_intersection">
      <description>Indicates if the shaker checks camera intersection.</description>
      <default_value>true</default_value>
    </field>
  </fields>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
  <new_default_value name="base_item.artificial">true</new_default_value>
</item>
