=== Quipyowert2/bear/bear-factory/schema/0.5/item-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.gamned.org/bear/schema/0.5"
           xmlns="http://www.gamned.org/bear/schema/0.5"
           elementFormDefault="qualified">
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="inherit"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="fields"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="new_default_value"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="remove_field"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:string" use="required"/>
      <xs:attribute name="category" type="xs:string" use="required"/>
      <xs:attribute name="box_color" type="xs:string"/>
      <xs:attribute name="fixable" type="xs:boolean" default="true"/>
      <xs:attribute name="url" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="description" type="xs:string"/>
  
  <xs:element name="inherit">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="class"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" ref="description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="set" />
        <xs:element minOccurs="0" maxOccurs="1" ref="interval" />
        <xs:element name="default_value" minOccurs="0" maxOccurs="1" type="xs:string" />
	<xs:element minOccurs="0" maxOccurs="unbounded" ref="after" />
      </xs:sequence>

      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="animation"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="font"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="item_reference"/>
            <xs:enumeration value="real"/>
            <xs:enumeration value="sample"/>
            <xs:enumeration value="sprite"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="u_integer"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" type="xs:ID" use="required"/>
      <xs:attribute name="required" type="xs:boolean" default="false"/>
      <xs:attribute name="list" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="after">
    <xs:complexType>
      <xs:attribute name="field" type="xs:IDREF" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="set">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="element">
          <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interval">
    <xs:complexType>
      <xs:attribute name="from" type="xs:decimal" use="required"/>
      <xs:attribute name="to" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="new_default_value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="remove_field" type="xs:string"/>

</xs:schema>

=== Quipyowert2/bear/bear-factory/item-description/generic/expr/linear_binary_expression_creator.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::linear_binary_expression_creator" category="-abstract-" box_color="#69DAFF" fixable="false">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::with_linear_expression_creation</class>
  </inherit>
  <fields>
    <field type="item_reference" name="binary_expression_creator.left_operand" required="true">
      <description>The left operand of the expression.</description>
      <set>
        <element value="bear::with_linear_expression_creation"/>
      </set>
    </field>
    <field type="item_reference" name="binary_expression_creator.right_operand" required="true">
      <description>The right operand of the expression.</description>
      <set>
        <element value="bear::with_linear_expression_creation"/>
      </set>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/link/base_link_visual.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::base_link_visual" category="-abstract-" fixable="false" url="http://www.gamned.org/wiki/index.php/base_link_visual">
  <inherit>
    <class>bear::base_item</class>
  </inherit>
  <description>Base class to display a link between two items.</description>
  <fields>
    <field type="item_reference" name="base_link_visual.start_item">
      <description>
        The item to use as reference for the start extremity.
      </description>
      <default_value>none</default_value>
    </field>
    <field type="item_reference" name="base_link_visual.end_item">
      <description>
        The item to use as reference for the end extremity.
      </description>
      <default_value>none</default_value>
    </field>
    <field type="string" name="base_link_visual.start_origin.x">
      <description>
        The x position of the start extremity in the reference item.
      </description>
      <set>
        <element value="left"/>
        <element value="right"/>
        <element value="middle"/>
      </set>
      <default_value>middle</default_value>
    </field>
    <field type="string" name="base_link_visual.start_origin.y">
      <description>
        The y position of the start extremity in the reference item.
      </description>
      <set>
        <element value="top"/>
        <element value="bottom"/>
        <element value="middle"/>
      </set>
      <default_value>middle</default_value>
    </field>
    <field type="string" name="base_link_visual.end_origin.x">
      <description>
        The x position of the end extremity in the reference item.
      </description>
      <set>
        <element value="left"/>
        <element value="right"/>
        <element value="middle"/>
      </set>
      <default_value>middle</default_value>
    </field>
    <field type="string" name="base_link_visual.end_origin.y">
      <description>
        The y position of the end extremity in the reference item.
      </description>
      <set>
        <element value="top"/>
        <element value="bottom"/>
        <element value="middle"/>
      </set>
      <default_value>middle</default_value>
    </field>
    <field type="real" name="base_link_visual.start_delta.x">
      <description>
        Delta to apply on the x-position of the start extremity.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_link_visual.start_delta.y">
      <description>
        Delta to apply on the y-position of the start extremity.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_link_visual.end_delta.x">
      <description>
        Delta to apply on the x-position of the end extremity.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_link_visual.end_delta.y">
      <description>
        Delta to apply on the y-position of the end extremity.
      </description>
      <default_value>0</default_value>
    </field>
  </fields>
  <new_default_value name="base_item.artificial">true</new_default_value>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/base_item.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::base_item" category="-abstract-" url="http://www.gamned.org/wiki/index.php/base_item">
  <fields>
    <field type="boolean" name="base_item.artificial">
      <description>
        Tell if the item is artificial. The physics will not be applied to it.
      </description>
      <default_value>false</default_value>
    </field>
    <field type="boolean" name="base_item.can_move_items">
      <description>
        Tell if the item can move other items.
      </description>
      <default_value>true</default_value>
    </field>
    <field type="boolean" name="base_item.global">
      <description>
        Tell if the item is global. The item will progress even if he is not
        near a player.
      </description>
      <default_value>false</default_value>
    </field>
    <field type="boolean" name="base_item.phantom">
      <description>
        Tell if the item is a phantom. The item will never be aligned by a wall
        or anything.
      </description>
      <default_value>false</default_value>
    </field>
    <field type="real" name="base_item.position.left">
      <description>
        Position of the left edge of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.position.bottom">
      <description>
        Position of the bottom edge of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="integer" name="base_item.position.depth">
      <description>
        Z-coordinate of the item in the layer.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.size.height">
      <description>
        The height of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.size.width">
      <description>
        The width of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.mass">
      <description>
        The mass of the item.
      </description>
      <default_value>infinity</default_value>
    </field>
    <field type="real" name="base_item.density">
      <description>
        The density of the item.
      </description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="base_item.elasticity">
      <description>
        The elasticity of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.hardness">
      <description>
        The hardness of the item.
      </description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="base_item.system_angle">
      <description>
        Angle applied to the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="boolean" name="base_item.fixed.x">
      <description>
        Tell if the item is fixed on x-coordinate.
      </description>
      <default_value>false</default_value>
      <after field="base_item.position.left"/>
      <after field="base_item.size.width"/>
    </field>
    <field type="boolean" name="base_item.fixed.y">
      <description>
       Tell if the item is fixed on y-coordinate.
      </description>
      <default_value>false</default_value>
      <after field="base_item.position.bottom"/>
      <after field="base_item.size.height"/>
    </field>
    <field type="boolean" name="base_item.fixed.z">
      <description>
        Tell if the item is fixed on z-coordinate.
      </description>
      <default_value>true</default_value>
      <after field="base_item.position.depth"/>
    </field>
    <field type="real" name="base_item.speed.x">
      <description>
        The initial horizontal speed of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.speed.y">
      <description>
        The initial vertical speed of the item.
      </description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="base_item.angular_speed">
      <description>
        The initial angular speed of the item.
      </description>
      <default_value>0</default_value>
    </field>

    <field type="boolean" name="base_item.free_system">
      <description>
        Tell if the system angle of the item is not modified by the collisions.
      </description>
      <default_value>false</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/item_brick/item_with_restricted_z_collision.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::item_with_restricted_z_collision" category="-abstract-" url="http://www.gamned.org/wiki/index.php/item_with_restricted_z_collision">
  <fields>
    <field type="integer" name="item_with_restricted_z_collision.min_z_for_collision">
      <description>
        Minimum z-position of the other item to be aligned.
      </description>
      <default_value>-infinity</default_value>
    </field>
    <field type="integer" name="item_with_restricted_z_collision.max_z_for_collision">
      <description>
        Maximum z-position of the other item to be aligned.
      </description>
      <default_value>infinity</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/friction_rectangle_creator.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::friction_rectangle_creator" category="control" fixable="false" box_color="#C0C0C0" url="http://www.gamned.org/wiki/index.php/friction_rectangle_creator">
  <inherit>
    <class>bear::base_item</class>
  </inherit>
  <description>This class adds a universe::friction_rectangle in the world then dies.</description>
  <fields>
    <field type="real" name="friction_rectangle_creator.friction">
      <description>The friction in the rectangle.</description>
      <default_value>1</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/forced_movement/forced_movement_toggle.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::forced_movement_toggle" category="control/movement" box_color="#F9FF7A" url="http://www.gamned.org/wiki/index.php/forced_movement_toggle">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::item_with_toggle</class>
    <class>bear::forced_movement_applicator</class>
  </inherit>
  <description>This class applies a forced movement to an item when activated.</description>
  <fields>
    <field type="boolean" name="forced_movement_toggle.apply_to_activator">
      <description>Tell if the movement has to be applied to the activator of the toggle
        too.</description>
      <default_value>false</default_value>
    </field>
  </fields>
  <new_default_value name="base_item.artificial">true</new_default_value>
  <new_default_value name="base_item.phantom">true</new_default_value>
  <new_default_value name="base_item.can_move_items">false</new_default_value>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/lines.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::lines" category="decoration" box_color="#BE41D1" url="http://www.gamned.org/wiki/index.php/lines" fixable="false">
  <inherit>
    <class>bear::base_item</class>
    <class>bear::basic_renderable_item</class>
  </inherit>
  <description>This item creates several instances of bear::line to
    draw a line between items.</description>
  <fields>
    <field type="item_reference" name="lines.ends" list="true">
      <description>The ends of the segments of the line.</description>
      <default_value>none</default_value>
    </field>
    <field type="real" name="lines.width">
      <description>The width of the line.</description>
      <default_value>1</default_value>
    </field>
  </fields>
</item>

=== Quipyowert2/bear/bear-factory/item-description/generic/world_parameters.xml
<?xml version="1.0" encoding="utf-8"?>
<item xmlns="http://www.gamned.org/bear/schema/0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gamned.org/bear/schema/0.5 http://www.gamned.org/bear/schema/0.5/item-description.xsd" class="bear::world_parameters" category="control" fixable="false" box_color="#C0C0C0" url="http://www.gamned.org/wiki/index.php/world_parameters">
  <inherit>
    <class>bear::base_item</class>
  </inherit>
  <description>This class defines the parameters of the world then dies.</description>
  <fields>
    <field type="real" name="world_parameters.gravity.x">
      <description>The x value of the gravity.</description>
      <default_value>0</default_value>
    </field>
    <field type="real" name="world_parameters.gravity.y">
      <description>The y value of the gravity.</description>
      <default_value>-9.81</default_value>
    </field>
    <field type="real" name="world_parameters.speed_epsilon.x">
      <description>The value under which the absolute value of the speed is considered to be equal to
        zero on the x axis.</description>
      <default_value>0.01</default_value>
    </field>
    <field type="real" name="world_parameters.speed_epsilon.y">
      <description>The value under which the absolute value of the speed is considered to be equal to
        zero on the y axis.</description>
      <default_value>0.01</default_value>
    </field>
    <field type="real" name="world_parameters.angular_speed_epsilon">
      <description>The value under which the absolute value of the angular speed is considered to be equal to zero.</description>
      <default_value>0.01</default_value>
    </field>
    <field type="real" name="world_parameters.unit">
      <description>The number of units of the world in a meter.</description>
      <default_value>3000</default_value>
    </field>
    <field type="real" name="world_parameters.default_friction">
      <description>Default friction applied to the items.</description>
      <default_value>1</default_value>
    </field>
    <field type="real" name="world_parameters.default_density">
      <description>Default density of the world.</description>
      <default_value>0</default_value>
    </field>
    <field type="string" name="world_parameters.default_environment">
      <description>Default environment of the world.</description>
      <set>
        <element value="air_environment"/>
        <element value="fire_environment"/>
        <element value="ice_environment"/>
        <element value="water_environment"/>
      </set>
      <default_value>"air_environment"</default_value>
    </field>
  </fields>
</item>
